# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.1.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant-Ubuntu-Box"

    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  config.vm.provision "shell", path: "shell.sh"
end
