# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "chenhan/ubuntu-mate-desktop-20.04"

  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Workbox"
    vb.gui = true
    vb.memory = "4096"
    vb.customize ["modifyvm", :id, "--audio", "coreaudio"]
    vb.customize ["modifyvm", :id, "--audiocontroller", "ac97"]
    vb.customize ["modifyvm", :id, "--audioin", "on"]
    vb.customize ["modifyvm", :id, "--audioout", "on"]
  end

  config.vm.provision "file", source:"~/.ssh/Workbox-vm-key", destination:"~/.ssh/Workbox-vm-key"
  config.vm.provision "shell", path: "shell.sh"
end
